In [1]:
# 1. Palindrome Check
def is_palindrome(s):
    return s == s[::-1]

string = input("Enter a string: ")
if is_palindrome(string):
    print(f"'{string}' is a palindrome.")
else:
    print(f"'{string}' is not a palindrome.")

Enter a string:  wow


'wow' is a palindrome.


In [3]:
# 2. Squares of numbers using loop with user input

numbers = list(map(int, input("Enter numbers separated by space: ").split()))

squares = []
for x in numbers:
    squares.append(x**2)

print("Squares:", squares)


Enter numbers separated by space:  1 2 3 4 5


Squares: [1, 4, 9, 16, 25]


In [7]:
# 3. DataFrame of 5 students and marks > 80 with user input
import pandas as pd

students = []
marks = []

for i in range(5):
    name = input(f"Enter name of student {i+1}: ")
    mark = int(input(f"Enter marks of {name}: "))
    students.append(name)
    marks.append(mark)

data = {
    "Student": students,
    "Marks": marks
}

df_students = pd.DataFrame(data)

print("\nAll Students Data:")
print(df_students)

print("\nStudents with marks > 80:")
print(df_students[df_students["Marks"] > 80])


Enter name of student 1:  Bhargav
Enter marks of Bhargav:  89
Enter name of student 2:  Ravi
Enter marks of Ravi:  67
Enter name of student 3:  Rahul
Enter marks of Rahul:  78
Enter name of student 4:  Animesh
Enter marks of Animesh:  89
Enter name of student 5:  Shreyas
Enter marks of Shreyas:  89



All Students Data:
   Student  Marks
0  Bhargav     89
1     Ravi     67
2    Rahul     78
3  Animesh     89
4  Shreyas     89

Students with marks > 80:
   Student  Marks
0  Bhargav     89
3  Animesh     89
4  Shreyas     89


In [8]:
# 4. 5x5 random integer array
import numpy as np

arr = np.random.randint(1, 101, size=(5, 5))
print("\n5x5 Random Array:")
print(arr)



5x5 Random Array:
[[70 47 32 11 42]
 [52 89 87 53 36]
 [17  9 65 29 93]
 [88 27 45 90 78]
 [20 88 15 15 67]]


In [9]:
# 5. DataFrame of products
products = {
    "Product Name": ["Laptop", "Phone", "Headphones", "Keyboard", "Mouse"],
    "Price": [60000, 30000, 2000, 1500, 800],
    "Category": ["Electronics", "Electronics", "Accessories", "Accessories", "Accessories"]
}

df_products = pd.DataFrame(products)
df_products["Discounted Price"] = df_products["Price"] * 0.9

print("\nProducts with Discounted Price:")
print(df_products)

print("\nProducts cheaper than 500:")
print(df_products[df_products["Price"] < 500])


Products with Discounted Price:
  Product Name  Price     Category  Discounted Price
0       Laptop  60000  Electronics           54000.0
1        Phone  30000  Electronics           27000.0
2   Headphones   2000  Accessories            1800.0
3     Keyboard   1500  Accessories            1350.0
4        Mouse    800  Accessories             720.0

Products cheaper than 500:
Empty DataFrame
Columns: [Product Name, Price, Category, Discounted Price]
Index: []
